"""add duration to workouts

Revision ID: 000a66aa312b
Revises: 4e2e9502a269
Create Date: 2026-04-26 14:32:56.672890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000a66aa312b'
down_revision = '4e2e9502a269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
